- hosts: alpina
  roles:
    - docker_host
    - alpina
  post_tasks:
    - name: Docker prune objects
      docker_prune:
        containers: true
        # Keep images for building grafana
        images: true
        images_filters:
          until: "720h"
        networks: true
        volumes: true
        builder_cache: false
