- hosts: docker_hosts
  roles:
    - docker_host
    - traefik
    - authentik
    - gitea
    - nextcloud
    - jellyfin
    - arrstack
  post_tasks:
    - name: Docker prune objects
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
