- hosts: all
  roles:
    - common
  pre_tasks:
  - name: Set fact for clean desired of docker objects and compose files
    set_fact:
      # clean_desired_arg is an extra variable passed to the playbook
      clean_desired: "{{ clean_desired_arg | bool }}"


- name: Install services
  import_playbook: services.yml
