# https://stackoverflow.com/questions/41667864/can-the-templates-module-handle-multiple-templates-directories

- name: Ensure {{ stack }} stack directory exists
  file:
    path: "{{ current_stack_dest }}"
    state: directory
    mode: "700"

- name: Ensure directory structure exists
  file:
    path: "{{ current_stack_dest }}/{{ item.path }}"
    state: directory
    mode: "700"
  loop: "{{ lookup('community.general.filetree', current_stack_source) }}"
  when: item.state == "directory"

- name: Generate {{ current_stack_name }} deployment from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ current_stack_dest }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    mode: "600"
  loop: "{{ lookup('community.general.filetree', current_stack_source) }}"
  when: item.state == "file"

- name: Deploy docker-compose for {{ current_stack_name }}
  community.docker.docker_compose_v2:
    project_src: "{{ current_stack_dest }}"
    state: present
    pull: always
    remove_orphans: yes
  register: docker_compose_output

- debug:
    var: docker_compose_output
