# https://stackoverflow.com/questions/41667864/can-the-templates-module-handle-multiple-templates-directories

- name: Ensure {{ stack }} stack directory exists
  file:
    path: "{{ current_stack_dest }}"
    state: directory
    mode: "700"

- name: Ensure directory structure exists
  file:
    path: "{{ current_stack_dest }}/{{ item.path }}"
    state: directory
    mode: "700"
  loop: "{{ lookup('community.general.filetree', current_stack_source) }}"
  when: item.state == "directory"

- name: Generate {{ current_stack_name }} deployment from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ current_stack_dest }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    mode: "600"
  loop: "{{ lookup('community.general.filetree', current_stack_source) }}"
  when: item.state == "file"

- name: Deploy docker-compose for {{ current_stack_name }}
  command: docker compose -f "{{ current_stack_dest }}/docker-compose.yml" up -d --pull always --remove-orphans
  register: docker_compose_output
  # Not perfect idempotency, but the built-in docker_compose module doesn't support docker-compose v2
  # And of course there's an IPv6 bug in docker-compose v1, smh
  # https://github.com/docker/compose/issues/7670
  changed_when: "'created' in docker_compose_output.stderr.lower()"
  failed_when: docker_compose_output.rc != 0

- debug:
    var: docker_compose_output
