- name: Register uid of remote user
  command: id -u
  register: remote_uid_command
  changed_when: false

- name: Set fact for uid
  set_fact:
    remote_uid: "{{ remote_uid_command.stdout }}"

- name: Ensure alpina directory exists
  file:
    state: directory
    path: "{{ alpina_svc_path }}"
    mode: "700"

- name: Deploy collection services
  vars:
    collection: services
    stacks:
      - traefik
      - monitoring
      - authentik
      - minio
  import_tasks: deploy_collection.yml

- name: Deploy collection apps
  vars:
    collection: apps
    stacks:
      - gitea
      - nextcloud
      - jellyfin
      - arrstack
  import_tasks: deploy_collection.yml
