- name: Upgrade Debian packages
  become: yes
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    autoremove: yes
    state: latest
  register: apt_upgrades

- name: Reboot if needed
  become: yes
  ansible.builtin.reboot:
  when: apt_upgrades.changed
