- name: Upgrade alpine packages
  community.general.apk:
    upgrade: yes
    update_cache: yes
  register: apk_upgrades

- name: Install alpine packages
  community.general.apk:
    name:
      - qemu-guest-agent
      - dhcpcd
      - python3
      - fish
      - docker
      - docker-compose
      - docker-fish-completion
      - docker-compose-fish-completion
      - zfs
    state: latest
    update_cache: yes
  register: apk_installs

- name: Enable qemu-guest-agent service
  service:
    name: qemu-guest-agent
    runlevel: boot
    enabled: yes

- name: Enable zfs-import service
  service:
    name: zfs-import
    runlevel: sysinit
    enabled: yes

- name: Enable zfs-mount service
  service:
    name: zfs-mount
    runlevel: sysinit
    enabled: yes

- name: Enable docker service
  service:
    name: docker
    enabled: yes

- name: Reboot if needed
  reboot:
  when: apk_upgrades.changed or apk_installs.changed
